//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.luvinbox.domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.luvinbox.domain.Properties.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string enumDegreeCollege {
            get {
                return ResourceManager.GetString("enumDegreeCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High school.
        /// </summary>
        public static string enumDegreeHighSchool {
            get {
                return ResourceManager.GetString("enumDegreeHighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBA.
        /// </summary>
        public static string enumDegreeMBA {
            get {
                return ResourceManager.GetString("enumDegreeMBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string enumDocCPF {
            get {
                return ResourceManager.GetString("enumDocCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string enumDocID {
            get {
                return ResourceManager.GetString("enumDocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIN.
        /// </summary>
        public static string enumDocIF {
            get {
                return ResourceManager.GetString("enumDocIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Documents.
        /// </summary>
        public static string enumDocOthers {
            get {
                return ResourceManager.GetString("enumDocOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string enumDocPassport {
            get {
                return ResourceManager.GetString("enumDocPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNE.
        /// </summary>
        public static string enumDocRNE {
            get {
                return ResourceManager.GetString("enumDocRNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver License.
        /// </summary>
        public static string enumDriverLicense {
            get {
                return ResourceManager.GetString("enumDriverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string enumGenderFemale {
            get {
                return ResourceManager.GetString("enumGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string enumGenderMale {
            get {
                return ResourceManager.GetString("enumGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        public static string enumMaritalStsDivorced {
            get {
                return ResourceManager.GetString("enumMaritalStsDivorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string enumMaritalStsMarried {
            get {
                return ResourceManager.GetString("enumMaritalStsMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separeted.
        /// </summary>
        public static string enumMaritalStsSeparated {
            get {
                return ResourceManager.GetString("enumMaritalStsSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string enumMaritalStsSingle {
            get {
                return ResourceManager.GetString("enumMaritalStsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildowed.
        /// </summary>
        public static string enumMaritalStsWidowed {
            get {
                return ResourceManager.GetString("enumMaritalStsWidowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string enumMaster {
            get {
                return ResourceManager.GetString("enumMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhD.
        /// </summary>
        public static string enumPhD {
            get {
                return ResourceManager.GetString("enumPhD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos Graduate.
        /// </summary>
        public static string enumPostgraduate {
            get {
                return ResourceManager.GetString("enumPostgraduate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy.
        /// </summary>
        public static string frmDateDataN {
            get {
                return ResourceManager.GetString("frmDateDataN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{5}([-]|\s*)?(\d{4})?$.
        /// </summary>
        public static string frmZipCodeFmt {
            get {
                return ResourceManager.GetString("frmZipCodeFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Zip code.
        /// </summary>
        public static string InvalidZipCode {
            get {
                return ResourceManager.GetString("InvalidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string lblAccountNumber {
            get {
                return ResourceManager.GetString("lblAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblAddCity {
            get {
                return ResourceManager.GetString("lblAddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        public static string lblAddComplement {
            get {
                return ResourceManager.GetString("lblAddComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblAddCountry {
            get {
                return ResourceManager.GetString("lblAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidade.
        /// </summary>
        public static string lblAddLocal {
            get {
                return ResourceManager.GetString("lblAddLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lblAddNumber {
            get {
                return ResourceManager.GetString("lblAddNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblAddState {
            get {
                return ResourceManager.GetString("lblAddState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string lblAddZipCode {
            get {
                return ResourceManager.GetString("lblAddZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrress.
        /// </summary>
        public static string lblAdrress {
            get {
                return ResourceManager.GetString("lblAdrress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Address.
        /// </summary>
        public static string lblAlternativeAddress {
            get {
                return ResourceManager.GetString("lblAlternativeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank branch.
        /// </summary>
        public static string lblBankBranch {
            get {
                return ResourceManager.GetString("lblBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank code.
        /// </summary>
        public static string lblBankCode {
            get {
                return ResourceManager.GetString("lblBankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Info.
        /// </summary>
        public static string lblBankInfo {
            get {
                return ResourceManager.GetString("lblBankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string lblBirthday {
            get {
                return ResourceManager.GetString("lblBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Contact.
        /// </summary>
        public static string lblCommercialContact {
            get {
                return ResourceManager.GetString("lblCommercialContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string lblCompanyName {
            get {
                return ResourceManager.GetString("lblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string lblDegree {
            get {
                return ResourceManager.GetString("lblDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblDocumentNumber {
            get {
                return ResourceManager.GetString("lblDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string lblFamilyName {
            get {
                return ResourceManager.GetString("lblFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy name.
        /// </summary>
        public static string lblFantasyName {
            get {
                return ResourceManager.GetString("lblFantasyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded in.
        /// </summary>
        public static string lblFoundedIn {
            get {
                return ResourceManager.GetString("lblFoundedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Physical Store.
        /// </summary>
        public static string lblHasPhysicalStore {
            get {
                return ResourceManager.GetString("lblHasPhysicalStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string lblImageURL {
            get {
                return ResourceManager.GetString("lblImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo URL.
        /// </summary>
        public static string lblLogoURL {
            get {
                return ResourceManager.GetString("lblLogoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Address.
        /// </summary>
        public static string lblMainAddress {
            get {
                return ResourceManager.GetString("lblMainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        public static string lblMaritalStatus {
            get {
                return ResourceManager.GetString("lblMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string lblMiddleName {
            get {
                return ResourceManager.GetString("lblMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lblMobileNumber {
            get {
                return ResourceManager.GetString("lblMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lblNumber {
            get {
                return ResourceManager.GetString("lblNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string lblOff {
            get {
                return ResourceManager.GetString("lblOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Price.
        /// </summary>
        public static string lblOffPrice {
            get {
                return ResourceManager.GetString("lblOffPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Form.
        /// </summary>
        public static string lblPaymentForm {
            get {
                return ResourceManager.GetString("lblPaymentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Id.
        /// </summary>
        public static string lblPaymentId {
            get {
                return ResourceManager.GetString("lblPaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Previous Status.
        /// </summary>
        public static string lblPaymentPreviousStatus {
            get {
                return ResourceManager.GetString("lblPaymentPreviousStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Status.
        /// </summary>
        public static string lblPaymentStatus {
            get {
                return ResourceManager.GetString("lblPaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Success.
        /// </summary>
        public static string lblPaymentSuccess {
            get {
                return ResourceManager.GetString("lblPaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Token.
        /// </summary>
        public static string lblPaymentToken {
            get {
                return ResourceManager.GetString("lblPaymentToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string lblPaymentType {
            get {
                return ResourceManager.GetString("lblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number is required.
        /// </summary>
        public static string RequiredAccountNumber {
            get {
                return ResourceManager.GetString("RequiredAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank branch is required.
        /// </summary>
        public static string RequiredBankBranch {
            get {
                return ResourceManager.GetString("RequiredBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank code is required.
        /// </summary>
        public static string RequiredBankCode {
            get {
                return ResourceManager.GetString("RequiredBankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string RequiredCity {
            get {
                return ResourceManager.GetString("RequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is required.
        /// </summary>
        public static string RequiredCompanyName {
            get {
                return ResourceManager.GetString("RequiredCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        public static string RequiredCountry {
            get {
                return ResourceManager.GetString("RequiredCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name is Required.
        /// </summary>
        public static string RequiredCustomerName {
            get {
                return ResourceManager.GetString("RequiredCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required.
        /// </summary>
        public static string RequiredDate {
            get {
                return ResourceManager.GetString("RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is required.
        /// </summary>
        public static string RequiredDocument {
            get {
                return ResourceManager.GetString("RequiredDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familly name is requied.
        /// </summary>
        public static string RequiredFamilyName {
            get {
                return ResourceManager.GetString("RequiredFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy name is required.
        /// </summary>
        public static string RequiredFantasyName {
            get {
                return ResourceManager.GetString("RequiredFantasyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded in is required.
        /// </summary>
        public static string RequiredFoundedIn {
            get {
                return ResourceManager.GetString("RequiredFoundedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local is required.
        /// </summary>
        public static string RequiredLocal {
            get {
                return ResourceManager.GetString("RequiredLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo site is required.
        /// </summary>
        public static string RequiredLogoSite {
            get {
                return ResourceManager.GetString("RequiredLogoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is requied.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is required.
        /// </summary>
        public static string RequiredNumber {
            get {
                return ResourceManager.GetString("RequiredNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is required.
        /// </summary>
        public static string RequiredNumber1 {
            get {
                return ResourceManager.GetString("RequiredNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        public static string RequiredState {
            get {
                return ResourceManager.GetString("RequiredState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code is required.
        /// </summary>
        public static string RequiredZipCode {
            get {
                return ResourceManager.GetString("RequiredZipCode", resourceCulture);
            }
        }
    }
}
